### ISSUE TITLE
Charter: attestation in or out of scope

### ISSUE THREAD

**Issue by bledvina** [bdetwiler/draft-detecting-unwanted-location-trackers#63]
some parties proposed attestation should be in scope and others proposed it should be out of scope for charter.

**Comment by ekr** [comment]
I don't think this is the right question. Attestation is a technical mechanism. The question to ask is whether fake trackers are part of the threat model.

**Comment by dkg** [comment]
i agree with @ekr here that attestation specifically isn't the right goal here.  I'm not sure what "fake trackers" means, though.  If there is any question about whether a tracker device is conformant or non-conformant (see #47), the charter needs to be clear about how that conformance or non-conformance is assessed (or not!) by other players in the ecosystem.

**Comment by ekr** [comment]
@dkg, you're right that I wasn't being clear.

The charter and the associated draft contain a set of requirements for how trackers are supposed to behave. These requirements are essential to providing the detection capability claimed by the specification. By hypothesis, trackers manufactured by "legitimate" vendors will be conformant and therefore detectable. The question I am trying to get at is whether it is possible to build a non-conformant tracker that will nevertheless be able to participate in the tracking system but is not detectable. That's what I meant by "fake" but hopefully this is a clearer statement.

I'm distinguishing this from the question of modifying a "legitimate" tracker because one might imagine a system in which:

1. Tracker vendors attested to conformance in some non-technical way
2. There was a technical attestation that a given tracker was manufactured by one of the aforementioned vendors.
3. That attestation was checked prior to letting that tracker participate in the network.

This would be intended to prevent other vendors from just making nonconformant trackers and having them accepted. In this case, it would be the "legitimate" vendor's responsibility to ensure that the tracker was hard to modify and if it were determined that it was easy to do so, that would be a vulnerability they should fix, but the protocol wouldn't engage with that other than, potentially blocklisting trackers of that model/vendor.
